# Generated by Django 5.1.4 on 2025-01-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerregistration',
            name='occupation',
            field=models.CharField(choices=[('student', 'Student'), ('self-employed', 'Self Employed'), ('business', 'Business'), ('other', 'Others')], default=3, max_length=14, verbose_name='Player Occupation'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Player Age'),
        ),
    ]
