# Generated by Django 5.1.4 on 2025-03-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playerregistration_occupation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerregistration',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Is the player got Selected'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='district',
            field=models.CharField(choices=[('Kanyakumari', 'Kanyakumari'), ('Tirunelveli', 'Tirunelveli'), ('Thoothukudi', 'Thoothukudi'), ('Tenkasi', 'Tenkasi'), ('Virudhunagar', 'Virudhunagar'), ('Ramanathapuram', 'Ramanathapuram'), ('Theni', 'Theni'), ('Madurai', 'Madurai'), ('Sivagangai', 'Sivagangai'), ('Dindigul', 'Dindigul'), ('Pudukkottai', 'Pudukkottai'), ('Thanjavur', 'Thanjavur'), ('Thiruvarur', 'Thiruvarur'), ('Nagapattinam', 'Nagapattinam'), ('Tiruchi', 'Tiruchi'), ('Ariyalur', 'Ariyalur'), ('Mayiladuthurai', 'Mayiladuthurai'), ('Perambalur', 'Perambalur'), ('Cuddalore', 'Cuddalore'), ('Pondicherry', 'Pondicherry'), ('Karaikkal', 'Karaikkal'), ('Chennai', 'Chennai'), ('Tiruvallur', 'Tiruvallur'), ('Kanchipuram', 'Kanchipuram'), ('Chengalpattu', 'Chengalpattu'), ('Tiruvannamalai', 'Tiruvannamalai'), ('Tirupattur', 'Tirupattur'), ('Vellore', 'Vellore'), ('Ranipet', 'Ranipet'), ('Kallakkurichi', 'Kallakkurichi'), ('Villuppuram', 'Villuppuram'), ('Krishnagiri', 'Krishnagiri'), ('Dharmapuri', 'Dharmapuri'), ('Nilgiris', 'Nilgiris'), ('Erode', 'Erode'), ('Salem', 'Salem'), ('Coimbatore', 'Coimbatore'), ('Tiruppur', 'Tiruppur'), ('Namakkal', 'Namakkal'), ('Karur', 'Karur')], max_length=100, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='reg_id',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Register ID'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='zone',
            field=models.CharField(default='ZONE A', editable=False, max_length=10, verbose_name='Zone'),
        ),
    ]
