# Generated by Django 5.1.4 on 2025-03-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_playerregistration_is_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerregistration',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Player Points on Trails'),
        ),
    ]
