# Generated by Django 5.1.4 on 2025-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_playerregistration_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerregistration',
            name='points',
            field=models.IntegerField(default=-99, verbose_name='Player Points on Trails'),
        ),
    ]
